from  tkinter import*
top=Tk()
top.geometry("1400x1400")
top.title("icon")
top.config(bg="blue")
welcome=Label(top,text="WELCOME",font=('TimesNewRoman',20,'italic'),bg="white")
NAME=Label(top,text="NAME:",font=('TimesNewRoman',20,'italic'),bg="white")

CLASS=Label(top,text="CLASS:",font=('TimesNewRoman',20,'italic'),bg="white")
REG=Label(top,text="REGNO:",font=('TimesNewRoman',20,'italic'),bg="white")

DEPT=Label(top,text="DEPT:",font=('TimesNewRoman',20,'italic'),bg="white")

COLLEGE=Label(top,text="COLLEGE",font=('TimesNewRoman',20,'italic'),bg="white")

welcome.place(x=700,y=100)
def login():
    a=Frame(top,bg="blue",height=700,width=700)
    a.pack(fill=X)
    label=Label(a,text="secondpage",font=('TimesNewRoman',20,'italic'),bg="white",fg="black")
    label.place(x=700,y=100)
    box5=Entry(a,text="",font=('TimesNewRoman',20,'italic'),fg="black")
    box5.place(x=550,y=200)
    box6=Entry(a,text="",font=('TimesNewRoman',20,'italic'),fg="black")
    box6.place(x=550,y=300)
    
NAME.place(x=300,y=200)
CLASS.place(x=300,y=300)
REG.place(x=300,y=400)
DEPT.place(x=300,y=500)
COLLEGE.place(x=300,y=600)
box=Entry(top,text="",font=('TimesNewRoman',20,'italic'),fg="black")
box.place(x=550,y=200)
box1=Entry(top,text="",font=('TimesNewRoman',20,'italic'),fg="black")
box1.place(x=550,y=300)
box2=Entry(top,text="",font=('TimesNewRoman',20,'italic'),fg="black")
box2.place(x=550,y=400)
box3=Entry(top,text="",font=('TimesNewRoman',20,'italic'),fg="black")
box3.place(x=550,y=500)
box4=Entry(top,text="",font=('TimesNewRoman',20,'italic'),fg="black")
box4.place(x=550,y=600)
BUTTON=Button(top,text="sumit",  font=('TimesNewRoman',20,'italic'),bg="black",fg="white",activebackground="yellow",activeforeground="red",command=login)
BUTTON.place(x=700,y=700,height=70,width=150)
top.mainloop()
